---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "keycloak"
  hostPath:
    path: /var/lib/k3d-data/mycluster/keycloak-postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "keycloak"
  volumeName: keycloak-postgres-pv
